[target.xtensa-esp32-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"

[target.xtensa-esp32s2-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
rustflags = ["-C", "default-linker-libraries"]
runner = "espflash flash --monitor"

[unstable]
build-std = ["std", "panic_abort"]

[env]
ESP_IDF_VERSION = "release/v4.4"
ESP_IDF_SDKCONFIG_DEFAULTS = { value = "sdkconfig.defaults", relative = true }
ESP_IDF_TOOLS_INSTALL_DIR = { value = "global" }
