name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  compile:
    name: compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - riscv32imc-esp-espidf
          - xtensa-esp32-espidf
          - xtensa-esp32s2-espidf
          - xtensa-esp32s3-espidf
        idf-version:
          - release/v4.4
          - release/v5.0
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup risc-v toolchain
        if: matrix.target == 'riscv32imc-esp-espidf'
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy, rust-src

      - name: setup xtensa toolchain
        if: matrix.target != 'riscv32imc-esp-espidf'
        uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true

      - name: cargo fmt
        run: cargo fmt -- --check

      - name: cargo clippy
        env:
          ESP_IDF_VERSION: ${{ matrix.idf-version }}
          RUSTFLAGS: "${{ matrix.idf-version == 'release/v5.0' && '--cfg espidf_time64' || ''}}"
        run:
          cargo clippy --no-deps --target ${{ matrix.target }} -Zbuild-std=std,panic_abort
          -Zbuild-std-features=panic_immediate_abort

      - name: cargo build
        env:
          ESP_IDF_VERSION: ${{ matrix.idf-version }}
          RUSTFLAGS: "${{ matrix.idf-version == 'release/v5.0' && '--cfg espidf_time64' || ''}}"
        run:
          cargo build --target ${{ matrix.target }} -Zbuild-std=std,panic_abort
          -Zbuild-std-features=panic_immediate_abort
